// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///  options: DefaultFirebaseOptions.currentPlatform,
///  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIbWzKw9-B_TBPflhmUNqMEM4us5WcTQ',
    appId: '1:32903997838:web:19a9bbf1ccf8c73a045cdf',
    messagingSenderId: '32903997838',
    projectId: 'barangay-garbage-tracker',
    authDomain: 'barangay-garbage-tracker.firebaseapp.com',
    storageBucket: 'barangay-garbage-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSM68NmiKa7w5bW_GF5px2xd94W24X6Kc',
    appId: '1:32903997838:android:6b7ca1a764181324045cdf',
    messagingSenderId: '32903997838',
    projectId: 'barangay-garbage-tracker',
    storageBucket: 'barangay-garbage-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4yKGYR6I8VVnxwSr7W9fayjkopjWpw7A',
    appId: '1:32903997838:ios:fdb0d6f1c4ead155045cdf',
    messagingSenderId: '32903997838',
    projectId: 'barangay-garbage-tracker',
    storageBucket: 'barangay-garbage-tracker.appspot.com',
    iosBundleId: 'com.example.garbageTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4yKGYR6I8VVnxwSr7W9fayjkopjWpw7A',
    appId: '1:32903997838:ios:4a967b9bf786b9a3045cdf',
    messagingSenderId: '32903997838',
    projectId: 'barangay-garbage-tracker',
    storageBucket: 'barangay-garbage-tracker.appspot.com',
    iosBundleId: 'com.example.garbageTracker.RunnerTests',
  );
}
